=== stevygee/Animacion/media/animation/schema.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT darkRealm (character?,stateLayer+)>

<!ELEMENT character (attachedObject?)>
<!ATTLIST character speed CDATA #IMPLIED>

<!ELEMENT attachedObject (position,rotation)>
<!ATTLIST attachedObject type (weapon) #REQUIRED
                         bone CDATA #REQUIRED>
                         
<!ELEMENT position EMPTY>
<!ATTLIST position x CDATA #REQUIRED
                   y CDATA #REQUIRED
                   z CDATA #REQUIRED>
                   
<!ELEMENT rotation EMPTY>
<!ATTLIST rotation x CDATA #REQUIRED
                   y CDATA #REQUIRED
                   z CDATA #REQUIRED>

<!ELEMENT stateLayer (blendMask?,(state|transitionState)+)>
<!ATTLIST stateLayer name ID #REQUIRED
                     type (base|partial) #REQUIRED
                     startState IDREF #REQUIRED>

<!ELEMENT blendMask (bone+)>

<!ELEMENT bone EMPTY>
<!ATTLIST bone name CDATA #REQUIRED
               weight CDATA #REQUIRED>

<!ELEMENT state (blendTree, transitions, end?)>
<!ATTLIST state name ID #REQUIRED>

<!ELEMENT transitionState (transition?)>
<!ATTLIST transitionState from IDREF #REQUIRED
                          to IDREF #REQUIRED>

<!ELEMENT blendTree (clip|lerp|shortcut)>

<!ELEMENT clip EMPTY>
<!ATTLIST clip name CDATA #REQUIRED
               temporalPlayback (true|false) #IMPLIED
               speed CDATA #IMPLIED
               loop (true|false) #IMPLIED
               flags CDATA #IMPLIED>
               
<!ELEMENT lerp (clip|lerp|shortcut)+>
<!ATTLIST lerp blendFactor CDATA #REQUIRED
               flags CDATA #IMPLIED>
               
<!ELEMENT shortcut EMPTY>
<!ATTLIST shortcut state IDREF #REQUIRED
                   stateLayer IDREF #IMPLIED
                   flags CDATA #IMPLIED>
                   
<!ELEMENT transitions (transition*)>

<!ELEMENT transition EMPTY>
<!ATTLIST transition action CDATA #REQUIRED
                     targetState CDATA #IMPLIED
                     type (pop|linear|smooth) #REQUIRED
                     duration CDATA #IMPLIED>

<!ELEMENT end EMPTY>
<!ATTLIST end targetState IDREF #REQUIRED>

=== stevygee/Animacion/media/animation/eva.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE darkRealm SYSTEM "schema.dtd">

<!-- States for the PlayerCharacter -->

<darkRealm>
	<character speed="3.575"><!-- vorher 2.75 wobei moveSpeed / 27 die normale speed vom walkcycle ist -->
		<attachedObject type="weapon" bone="rightHand">
			<position x="16.2" y="-0.5" z="0.4"/><!-- x=arm-richtung, z=world-Y, y=links-rechts -->
			<rotation x="11.0" y="90.0" z="180.0"/><!-- y=um zeigefinger drehen, x=um arm-achse drehen -->
		</attachedObject>
	</character>
	
	
	
	
	<!-- Upper Body __________________________________________________________________________________________________________ -->
	<stateLayer name="upperbody" type="partial" startState="noweaponIdle">
		<blendMask>
			<bone name="root" weight="0"/>
			<bone name="leftHip" weight="0"/>
			<bone name="rightHip" weight="0"/>
			<bone name="back1" weight="0"/>
			<bone name="back2" weight="1"/>
			<bone name="back3" weight="1"/>
		</blendMask>
		<state name="noweaponIdle">
			<blendTree>
				<shortcut state="idle" stateLayer="lowerbody"/>
			</blendTree>
			<transitions>
				<transition action="run" targetState="noweaponIdle_to_noweaponRunning" type="smooth" duration="0.25"/>
				<transition action="aim" targetState="noweaponIdle_to_aiming" type="smooth" duration="0.25"/>
			</transitions>
		</state>
		<state name="noweaponRunning">
			<blendTree>
				<shortcut state="running" stateLayer="lowerbody"/>
			</blendTree>
			<transitions>
				<transition action="stop" targetState="noweaponRunning_to_noweaponIdle" type="smooth" duration="0.13"/>
				<transition action="aim" targetState="noweaponRunning_to_aiming" type="smooth" duration="0.6"/>
			</transitions>
		</state>
		<state name="aiming">
			<blendTree>
				<lerp blendFactor="0.0" flags="aim_vertical1">
					<lerp blendFactor="0.0" flags="aim_vertical2">
						<clip name="aimUp" temporalPlayback="false"/>
						<clip name="aim" temporalPlayback="false"/>
					</lerp>
					<lerp blendFactor="0.0" flags="aim_vertical3">
						<clip name="aim" temporalPlayback="false"/>
						<clip name="aimDown" temporalPlayback="false"/>
					</lerp>
				</lerp>
			</blendTree>
			<transitions>
				<transition action="reload" targetState="reloading" type="pop" duration="3"/>
				<transition action="drop_weapon_idle" targetState="aiming_to_noweaponIdle" type="smooth" duration="0.3"/>
				<transition action="drop_weapon_run" targetState="aiming_to_noweaponRunning" type="smooth" duration="0.5"/>
			</transitions>
		</state>
		<state name="reloading">
			<blendTree>
				<clip name="aimDown" temporalPlayback="false"/><!-- reload anim -->
			</blendTree>
			<transitions>
				<!-- drop weapon while reload? -->
			</transitions>
			<end targetState="aiming"/>
		</state>
		
		
		
		<!-- Transition States _______________________________________________ -->
		<transitionState from="noweaponIdle" to="noweaponRunning"><transition action="stop" type="smooth" duration="0.13"/></transitionState>
        <transitionState from="noweaponIdle" to="aiming"><transition action="drop_weapon_idle" type="smooth" duration="0.25"/></transitionState>
        <transitionState from="noweaponRunning" to="noweaponIdle"><transition action="run" type="smooth" duration="0.25"/></transitionState>
        <transitionState from="noweaponRunning" to="aiming"><transition action="drop_weapon_run" type="smooth" duration="0.5"/></transitionState>
        <transitionState from="aiming" to="noweaponIdle"><transition action="aim" type="smooth" duration="0.25"/></transitionState>
        <transitionState from="aiming" to="noweaponRunning"><transition action="aim" type="smooth" duration="0.5"/></transitionState>
	</stateLayer>
	
	
	
	
	<!-- Lower Body __________________________________________________________________________________________________________ -->
	<stateLayer name="lowerbody" type="base" startState="idle">
		<blendMask>
			<bone name="root" weight="1"/>
			<bone name="leftHip" weight="1"/>
			<bone name="rightHip" weight="1"/>
			<bone name="back1" weight="1"/>
			<bone name="back2" weight="0"/>
			<bone name="back3" weight="0"/>
		</blendMask>
		<state name="idle">
			<blendTree>
				<clip name="idle"/>
			</blendTree>
			<transitions>
				<transition action="run" targetState="idle_to_running" type="smooth" duration="0.25"/>
			</transitions>
		</state>
		<state name="running">
			<blendTree>
				<clip name="run" speed="0.3" flags="character_speed"/><!--  speed="2.7"  -->
			</blendTree>
			<transitions>
				<transition action="stop" targetState="running_to_idle" type="smooth" duration="0.13"/>
			</transitions>
		</state>
		
		
		
		<!-- Transition States _______________________________________________ -->
		<transitionState from="idle" to="running"><transition action="stop" type="smooth" duration="0.13"/></transitionState>
		<transitionState from="running" to="idle"><transition action="run" type="smooth" duration="0.25"/></transitionState>
	</stateLayer>
</darkRealm>

=== stevygee/Animacion/media/animation/malezombie.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE darkRealm SYSTEM "schema.dtd">

<!-- States for the maleZombie -->

<darkRealm>
 	<character speed="1.25"/>
 	



	<!-- Upper Body __________________________________________________________________________________________________________ -->
	<stateLayer name="upperbody" type="partial" startState="idleLurking">
		<blendMask>
			<bone name="root" weight="0"/>
			<bone name="leftHip" weight="0"/>
			<bone name="rightHip" weight="0"/>
			<bone name="back1" weight="0"/>
			<bone name="back2" weight="1"/>
			<bone name="back3" weight="1"/>
		</blendMask>
		<state name="attacking">
			<blendTree>
				<clip name="attack"/>
			</blendTree>
			<transitions>
				<transition action="lurk" targetState="attacking_to_idleLurking" type="smooth" duration="0.5"/>
				<transition action="walk" targetState="attacking_to_walking" type="smooth" duration="0.5"/>
				<transition action="die" targetState="attacking_to_dying" type="smooth" duration="0.5"/>
			</transitions>
		</state>

		<state name="idleLurking">
			<blendTree>
				<shortcut state="idleLurking" stateLayer="lowerbody"/>
			</blendTree>
			<transitions>
				<transition action="walk" targetState="idleLurking_to_walking" type="smooth" duration="0.5"/>
				<transition action="threat" targetState="idleLurking_to_threating" type="smooth" duration="0.5"/>
				<transition action="die" targetState="idleLurking_to_dying" type="smooth" duration="0.5"/>

				<transition action="attack" targetState="idleLurking_to_attacking" type="smooth" duration="0.5"/>
			</transitions>
		</state>
		<state name="walking">
			<blendTree>
				<shortcut state="walking" stateLayer="lowerbody"/>
			</blendTree>
			<transitions>
				<transition action="lurk" targetState="walking_to_idleLurking" type="smooth" duration="0.5"/>
				<transition action="die" targetState="walking_to_dying" type="smooth" duration="0.5"/>

				<transition action="attack" targetState="walking_to_attacking" type="smooth" duration="0.5"/>
			</transitions>
		</state>
		<state name="threating">
			<blendTree>
				<shortcut state="threating" stateLayer="lowerbody"/>
			</blendTree>
			<transitions>
				<transition action="walk" targetState="threating_to_walking" type="smooth" duration="0.5"/>
				<transition action="die" targetState="threating_to_dying" type="smooth" duration="0.5"/>

				<transition action="attack" targetState="threating_to_attacking" type="smooth" duration="0.5"/>
			</transitions>
		</state>
		<state name="dying">
			<blendTree>
				<shortcut state="dying" stateLayer="lowerbody"/>
			</blendTree>
			<transitions>
			</transitions>
		</state>



		<!-- Transition States _______________________________________________ -->


		<!-- Attacking to ... _________________________ -->
		<transitionState from="attacking" to="idleLurking"><transition action="attack" type="smooth" duration="0.5"/></transitionState>
		<transitionState from="attacking" to="walking"><transition action="attack" type="smooth" duration="0.5"/></transitionState>
		<transitionState from="attacking" to="dying"/>


		<!-- Idle Lurking to ... _________________________ -->
		<transitionState from="idleLurking" to="walking"><transition action="lurk" type="smooth" duration="0.5"/></transitionState>
		<transitionState from="idleLurking" to="threating"/>
		<transitionState from="idleLurking" to="dying"/>
		
		<transitionState from="idleLurking" to="attacking"><transition action="stop" type="smooth" duration="0.5"/></transitionState>


		<!-- Walking Slow to ... _________________________ -->
		<transitionState from="walking" to="idleLurking"><transition action="walk" type="smooth" duration="0.5"/></transitionState>
		<transitionState from="walking" to="dying"/>
		
		<transitionState from="walking" to="attacking"><transition action="stop" type="smooth" duration="0.5"/></transitionState>


		<!-- Threating to ... _________________________ -->
		<transitionState from="threating" to="walking"/>
		<transitionState from="threating" to="dying"/>
		
		<transitionState from="threating" to="attacking"/>
	</stateLayer>




	<!-- Lower Body __________________________________________________________________________________________________________ -->
	<stateLayer name="lowerbody" type="base" startState="idleLurking">
		<blendMask>
			<bone name="root" weight="1"/>
			<bone name="leftHip" weight="1"/>
			<bone name="rightHip" weight="1"/>
			<bone name="back1" weight="1"/>
			<bone name="back2" weight="0"/>
			<bone name="back3" weight="0"/>
		</blendMask>
		<state name="idleLurking">
			<blendTree>
				<lerp blendFactor="0.0" flags="idle_weight">
					<clip name="idleA"/>
    				<clip name="idleB"/>
                </lerp>
			</blendTree>
			<transitions>
				<transition action="walk" targetState="idleLurking_to_walking" type="smooth" duration="0.5"/>
				<transition action="threat" targetState="idleLurking_to_threating" type="smooth" duration="0.5"/>
				<transition action="die" targetState="idleLurking_to_dying" type="smooth" duration="0.5"/>
			</transitions>
		</state>
		<state name="walking">
			<blendTree>
				<lerp blendFactor="0.0" flags="walk_weight">
					<clip name="walkA" speed="1.05" flags="character_speed"/>
    				<clip name="walkB" speed="1.5" flags="character_speed"/>
                </lerp>
			</blendTree>
			<transitions>
				<transition action="lurk" targetState="walking_to_idleLurking" type="smooth" duration="0.5"/>
				<transition action="die" targetState="walking_to_dying" type="smooth" duration="0.5"/>
			</transitions>
		</state>
		<state name="threating">
			<blendTree>
				<clip name="threat" loop="false"/>
			</blendTree>
			<transitions>
				<transition action="walk" targetState="threating_to_walking" type="smooth" duration="0.5"/>
				<transition action="die" targetState="threating_to_dying" type="smooth" duration="0.5"/>
			</transitions>
		</state>
		<state name="dying">
			<blendTree>
				<clip name="death" loop="false"/>
			</blendTree>
			<transitions>
			</transitions>
		</state>



		<!-- Transition States _______________________________________________ -->


		<!-- Idle Lurking to ... _________________________ -->
		<transitionState from="idleLurking" to="walking"><transition action="lurk" type="smooth" duration="0.5"/></transitionState>
		<transitionState from="idleLurking" to="threating"/>
		<transitionState from="idleLurking" to="dying"/>


		<!-- Walking Slow to ... _________________________ -->
		<transitionState from="walking" to="idleLurking"><transition action="walk" type="smooth" duration="0.5"/></transitionState>
		<transitionState from="walking" to="dying"/>


		<!-- Threating to ... _________________________ -->
		<transitionState from="threating" to="walking"/>
		<transitionState from="threating" to="dying"/>
	</stateLayer>
</darkRealm>
